parameters:
#    hflan_blog.example.class: hflan\BlogBundle\Example

services:
#    hflan_blog.example:
#        class: %hflan_blog.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
