parameters:
#    hflan_blog.example.class: hflan\BlogBundle\Example

services:
    form.type.roles:
        class: hflan\UserBundle\Form\Type\RolesType
        tags:
            - { name: form.type, alias: roles }
