parameters:
#    hflan_stream.example.class: hflan\StreamBundle\Example

services:
    hflan.twig.hflan_stream:
        class: hflan\StreamBundle\Twig\StreamExtension
        arguments:
            - @doctrine.orm.entity_manager
        tags:
            - { name: twig.extension }
