parameters:
#    hflan_page.example.class: hflan\PageBundle\Example

services:
#    hflan_page.example:
#        class: %hflan_page.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
