# Public

hflan_blog:
    pattern:  /{page}
    defaults: { _controller: hflanBlogBundle:Public:index, page:1 }
    requirements:
        page: \d+

hflan_blog_show:
    pattern:  /view/{slug}
    defaults: { _controller: hflanBlogBundle:Public:show }

# Admin

hflan_blog_admin:
    pattern:  /admin/{page}
    defaults: { _controller: hflanBlogBundle:Admin:index, page:1 }
    requirements:
        page: \d+

hflan_blog_new:
    pattern:  /admin/new
    defaults: { _controller: hflanBlogBundle:Admin:new }

hflan_blog_edit:
    pattern:  /admin/edit/{slug}
    defaults: { _controller: hflanBlogBundle:Admin:edit }
