parameters:
#    hflan_blog.example.class: hflan\BlogBundle\Example

services:
    form.type.radiobar:
        class: hflan\BlogBundle\Form\Type\RadioBarType
        arguments:
        tags:
            - { name: form.type, alias: radiobar }
    form.type.toggle:
        class: hflan\BlogBundle\Form\Type\ToggleType
        arguments:
        tags:
            - { name: form.type, alias: toggle }