fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"

fos_user_resetting:
    resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
    prefix: /resetting

fos_user_change_password:
    resource: "@FOSUserBundle/Resources/config/routing/change_password.xml"
    prefix: /profile

hflan_photos:
    resource: "@hflanPhotosBundle/Resources/config/routing.yml"
    prefix:   /photos

hflan_lan:
    resource: "@hflanLanBundle/Resources/config/routing.yml"
    prefix:   /lan

hflan_blog:
    resource: "@hflanBlogBundle/Resources/config/routing.yml"
    prefix:   /blog

