security:
    encoders:
        hflan\UserBundle\Entity\User: sha512

    role_hierarchy:
        ROLE_NEWSER:        ROLE_STAFF
        ROLE_RESPO:         ROLE_STAFF
        ROLE_GUESTBOOK:     ROLE_STAFF
        ROLE_PARTNER:       ROLE_STAFF
        ROLE_USER_MANAGER:  ROLE_STAFF
        ROLE_STREAM:        ROLE_STAFF
        ROLE_ADMIN:         [ROLE_NEWSER, ROLE_RESPO, ROLE_GUESTBOOK, ROLE_PARTNER, ROLE_USER_MANAGER, ROLE_REMOVE, ROLE_STREAM]
        ROLE_SUPER_ADMIN:   [ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    providers:
        fos_userbundle:
            id: fos_user.user_provider.username

    firewalls:
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            pattern: ^/
            anonymous:      true
            provider:       fos_userbundle
            form_login:
                csrf_provider: form.csrf_provider
                login_path: fos_user_security_login
                check_path: fos_user_security_check
            logout:
                path:       fos_user_security_logout
                target:     /
                invalidate_session: false
            remember_me:
                key:        %secret%

    access_control:
        - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: admin, role: ROLE_STAFF }
