# Team

hflan_register:
    pattern:  /register/{slug}
    defaults: { _controller: hflanLanBundle:Team:register, slug: null }

hflan_edit_team:
    pattern:  /register/step-2
    defaults: { _controller: hflanLanBundle:Team:edit }

hflan_pay_team:
    pattern:  /register/step-3
    defaults: { _controller: hflanLanBundle:Team:pay }

hflan_team_show:
    pattern:  /teams/{id}
    defaults: { _controller: hflanLanBundle:Team:show }

hflan_team_upgrade:
    pattern:  /teams/{id}/upgrade
    defaults: { _controller: hflanLanBundle:Team:upgrade }

hflan_team_downgrade:
    pattern:  /teams/{id}/downgrade
    defaults: { _controller: hflanLanBundle:Team:downgrade }

# Player

hflan_edit_player:
    pattern:  /player/{id}/edit
    defaults: { _controller: hflanLanBundle:Player:edit }

# Admin Event

hflan_event_new:
    pattern:  /events/new
    defaults: { _controller: hflanLanBundle:Event:new }

hflan_event_export:
    pattern:  /{slug}/export
    defaults: { _controller: hflanLanBundle:Event:export }

hflan_event_edit:
    pattern:  /{slug}/edit
    defaults: { _controller: hflanLanBundle:Event:edit }

hflan_event_remove:
    pattern:  /{slug}/remove
    defaults: { _controller: hflanLanBundle:Event:remove }

hflan_event_admin:
    pattern:  /events
    defaults: { _controller: hflanLanBundle:Event:index }

hflan_info:
    pattern:  /info
    defaults: { _controller: hflanLanBundle:Event:info }

# Admin Tournament

hflan_tournament_show:
    pattern:  /tournaments/{slug}
    defaults: { _controller: hflanLanBundle:Tournament:show }

hflan_tournament_edit:
    pattern:  /tournaments/{slug}/edit
    defaults: { _controller: hflanLanBundle:Tournament:edit }

hflan_tournament_remove:
    pattern:  /tournaments/{slug}/remove
    defaults: { _controller: hflanLanBundle:Tournament:remove }

hflan_tournament_export:
    pattern:  /tournaments/{slug}/export
    defaults: { _controller: hflanLanBundle:Tournament:export }

hflan_tournament_new:
    pattern:  /{slug}/tournaments/new
    defaults: { _controller: hflanLanBundle:Tournament:new }