# Admin

hflan_event_new:
    pattern:  /event/admin/new
    defaults: { _controller: hflanLanBundle:Event:new }

hflan_event_admin:
    pattern:  /event/admin
    defaults: { _controller: hflanLanBundle:Event:index }