# Team

hflan_register:
    pattern:  /register
    defaults: { _controller: hflanLanBundle:Team:register }

hflan_edit_team:
    pattern:  /register/step-2
    defaults: { _controller: hflanLanBundle:Team:edit }

# Player

hflan_edit_player:
    pattern:  /player/{id}/edit
    defaults: { _controller: hflanLanBundle:Player:edit }

# Admin Event

hflan_event_new:
    pattern:  /events/new
    defaults: { _controller: hflanLanBundle:Event:new }

hflan_event_edit:
    pattern:  /{slug}/edit
    defaults: { _controller: hflanLanBundle:Event:edit }

hflan_event_admin:
    pattern:  /events
    defaults: { _controller: hflanLanBundle:Event:index }

# Admin Tournament

hflan_tournament_edit:
    pattern:  /tournaments/{slug}/edit
    defaults: { _controller: hflanLanBundle:Tournament:edit }

hflan_tournament_new:
    pattern:  /{slug}/tournaments/new
    defaults: { _controller: hflanLanBundle:Tournament:new }