# Admin Event

hflan_event_new:
    pattern:  /events/new
    defaults: { _controller: hflanLanBundle:Event:new }

hflan_event_edit:
    pattern:  /{slug}/edit
    defaults: { _controller: hflanLanBundle:Event:edit }

hflan_event_admin:
    pattern:  /events
    defaults: { _controller: hflanLanBundle:Event:index }

# Admin Tournament

hflan_tournament_new:
    pattern:  /{slug}/tournaments/new
    defaults: { _controller: hflanLanBundle:Tournament:new }

hflan_tournament_edit:
    pattern:  /tournaments/{slug}/edit
    defaults: { _controller: hflanLanBundle:Tournament:edit }