# Admin Event

hflan_event_new:
    pattern:  /admin/event/new
    defaults: { _controller: hflanLanBundle:Event:new }

hflan_event_edit:
    pattern:  /admin/event/edit/{slug}
    defaults: { _controller: hflanLanBundle:Event:edit }

hflan_event_admin:
    pattern:  /admin/event
    defaults: { _controller: hflanLanBundle:Event:index }

# Admin Tournament

hflan_tournament_new:
    pattern:  /admin/event/add-tournament/{slug}
    defaults: { _controller: hflanLanBundle:Tournament:new }

hflan_tournament_edit:
    pattern:  /admin/tournament/edit/{slug}
    defaults: { _controller: hflanLanBundle:Tournament:edit }