parameters:
#    hflan_lan.example.class: hflan\LanBundle\Example

services:
#    hflan_lan.example:
#        class: %hflan_lan.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
