parameters:
#    hflan_lan.example.class: hflan\LanBundle\Example

services:
    form.type.datepicker:
        class: hflan\LanBundle\Form\Type\DatepickerType
        arguments:
        tags:
            - { name: form.type, alias: datepicker }
