hflan_photos:
    pattern:  /
    defaults: { _controller: hflanPhotosBundle:Public:index }

hflan_photos_album:
    pattern:  /{id}
    defaults: { _controller: hflanPhotosBundle:Public:album }
    requirements:
        id: \d+
