parameters:

services:
    hflan.twig.hflan_block:
        class: hflan\BlockBundle\Twig\BlockExtension
        arguments:
            - @doctrine.orm.entity_manager
            - @service_container
        tags:
            - { name: twig.extension }
