parameters:
#    hflan_document.example.class: hflan\DocumentBundle\Example

services:
#    hflan_document.example:
#        class: %hflan_document.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
